language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

# uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
matrix:
 allow_failures:
 - julia: nightly

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("MLStyle")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("MLStyle")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # add Documenter
  - julia -e 'using Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps)'
  # push documents to gh-pages
  - julia -e 'using Pkg; cd(Pkg.dir("MLStyle")); include(joinpath("docs", "make.jl"))'
